// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package employeemanagement.proxies;

public class CurrentWeatherRoot
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject currentWeatherRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmployeeManagement.CurrentWeatherRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Lat("Lat"),
		Lon("Lon"),
		Timezone("Timezone"),
		Timezone_offset("Timezone_offset"),
		CurrentWeather_CurrentWeatherRoot("EmployeeManagement.CurrentWeather_CurrentWeatherRoot");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CurrentWeatherRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CurrentWeatherRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject currentWeatherRootMendixObject)
	{
		if (currentWeatherRootMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, currentWeatherRootMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.currentWeatherRootMendixObject = currentWeatherRootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CurrentWeatherRoot.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static employeemanagement.proxies.CurrentWeatherRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return employeemanagement.proxies.CurrentWeatherRoot.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static employeemanagement.proxies.CurrentWeatherRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new employeemanagement.proxies.CurrentWeatherRoot(context, mendixObject);
	}

	public static employeemanagement.proxies.CurrentWeatherRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return employeemanagement.proxies.CurrentWeatherRoot.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Lat
	 */
	public final java.math.BigDecimal getLat()
	{
		return getLat(getContext());
	}

	/**
	 * @param context
	 * @return value of Lat
	 */
	public final java.math.BigDecimal getLat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lat.toString());
	}

	/**
	 * Set value of Lat
	 * @param lat
	 */
	public final void setLat(java.math.BigDecimal lat)
	{
		setLat(getContext(), lat);
	}

	/**
	 * Set value of Lat
	 * @param context
	 * @param lat
	 */
	public final void setLat(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lat)
	{
		getMendixObject().setValue(context, MemberNames.Lat.toString(), lat);
	}

	/**
	 * @return value of Lon
	 */
	public final java.math.BigDecimal getLon()
	{
		return getLon(getContext());
	}

	/**
	 * @param context
	 * @return value of Lon
	 */
	public final java.math.BigDecimal getLon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lon.toString());
	}

	/**
	 * Set value of Lon
	 * @param lon
	 */
	public final void setLon(java.math.BigDecimal lon)
	{
		setLon(getContext(), lon);
	}

	/**
	 * Set value of Lon
	 * @param context
	 * @param lon
	 */
	public final void setLon(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lon)
	{
		getMendixObject().setValue(context, MemberNames.Lon.toString(), lon);
	}

	/**
	 * @return value of Timezone
	 */
	public final java.lang.String getTimezone()
	{
		return getTimezone(getContext());
	}

	/**
	 * @param context
	 * @return value of Timezone
	 */
	public final java.lang.String getTimezone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Timezone.toString());
	}

	/**
	 * Set value of Timezone
	 * @param timezone
	 */
	public final void setTimezone(java.lang.String timezone)
	{
		setTimezone(getContext(), timezone);
	}

	/**
	 * Set value of Timezone
	 * @param context
	 * @param timezone
	 */
	public final void setTimezone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timezone)
	{
		getMendixObject().setValue(context, MemberNames.Timezone.toString(), timezone);
	}

	/**
	 * @return value of Timezone_offset
	 */
	public final java.lang.Integer getTimezone_offset()
	{
		return getTimezone_offset(getContext());
	}

	/**
	 * @param context
	 * @return value of Timezone_offset
	 */
	public final java.lang.Integer getTimezone_offset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Timezone_offset.toString());
	}

	/**
	 * Set value of Timezone_offset
	 * @param timezone_offset
	 */
	public final void setTimezone_offset(java.lang.Integer timezone_offset)
	{
		setTimezone_offset(getContext(), timezone_offset);
	}

	/**
	 * Set value of Timezone_offset
	 * @param context
	 * @param timezone_offset
	 */
	public final void setTimezone_offset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer timezone_offset)
	{
		getMendixObject().setValue(context, MemberNames.Timezone_offset.toString(), timezone_offset);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CurrentWeather_CurrentWeatherRoot
	 */
	public final employeemanagement.proxies.CurrentWeather getCurrentWeather_CurrentWeatherRoot() throws com.mendix.core.CoreException
	{
		return getCurrentWeather_CurrentWeatherRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentWeather_CurrentWeatherRoot
	 * @throws com.mendix.core.CoreException
	 */
	public final employeemanagement.proxies.CurrentWeather getCurrentWeather_CurrentWeatherRoot(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		employeemanagement.proxies.CurrentWeather result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CurrentWeather_CurrentWeatherRoot.toString());
		if (identifier != null) {
			result = employeemanagement.proxies.CurrentWeather.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CurrentWeather_CurrentWeatherRoot
	 * @param currentweather_currentweatherroot
	 */
	public final void setCurrentWeather_CurrentWeatherRoot(employeemanagement.proxies.CurrentWeather currentweather_currentweatherroot)
	{
		setCurrentWeather_CurrentWeatherRoot(getContext(), currentweather_currentweatherroot);
	}

	/**
	 * Set value of CurrentWeather_CurrentWeatherRoot
	 * @param context
	 * @param currentweather_currentweatherroot
	 */
	public final void setCurrentWeather_CurrentWeatherRoot(com.mendix.systemwideinterfaces.core.IContext context, employeemanagement.proxies.CurrentWeather currentweather_currentweatherroot)
	{
		if (currentweather_currentweatherroot == null) {
			getMendixObject().setValue(context, MemberNames.CurrentWeather_CurrentWeatherRoot.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CurrentWeather_CurrentWeatherRoot.toString(), currentweather_currentweatherroot.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return currentWeatherRootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final employeemanagement.proxies.CurrentWeatherRoot that = (employeemanagement.proxies.CurrentWeatherRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
