// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package employeemanagement.proxies;

public class Employee
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmployeeManagement.Employee";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EmployeeID("EmployeeID"),
		Designation("Designation"),
		DateOfJoining("DateOfJoining"),
		ContactInfo("ContactInfo"),
		DepartmentName("DepartmentName"),
		EmployeeName("EmployeeName"),
		EmailAddress("EmailAddress"),
		Employee_Department("EmployeeManagement.Employee_Department"),
		Employee_Account("EmployeeManagement.Employee_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Employee(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Employee(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject)
	{
		if (employeeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, employeeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.employeeMendixObject = employeeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Employee.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static employeemanagement.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return employeemanagement.proxies.Employee.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static employeemanagement.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new employeemanagement.proxies.Employee(context, mendixObject);
	}

	public static employeemanagement.proxies.Employee load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return employeemanagement.proxies.Employee.initialize(context, mendixObject);
	}

	public static java.util.List<employeemanagement.proxies.Employee> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> employeemanagement.proxies.Employee.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of EmployeeID
	 */
	public final java.lang.Integer getEmployeeID()
	{
		return getEmployeeID(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeID
	 */
	public final java.lang.Integer getEmployeeID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EmployeeID.toString());
	}

	/**
	 * Set value of EmployeeID
	 * @param employeeid
	 */
	public final void setEmployeeID(java.lang.Integer employeeid)
	{
		setEmployeeID(getContext(), employeeid);
	}

	/**
	 * Set value of EmployeeID
	 * @param context
	 * @param employeeid
	 */
	public final void setEmployeeID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer employeeid)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeID.toString(), employeeid);
	}

	/**
	 * @return value of Designation
	 */
	public final java.lang.String getDesignation()
	{
		return getDesignation(getContext());
	}

	/**
	 * @param context
	 * @return value of Designation
	 */
	public final java.lang.String getDesignation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Designation.toString());
	}

	/**
	 * Set value of Designation
	 * @param designation
	 */
	public final void setDesignation(java.lang.String designation)
	{
		setDesignation(getContext(), designation);
	}

	/**
	 * Set value of Designation
	 * @param context
	 * @param designation
	 */
	public final void setDesignation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String designation)
	{
		getMendixObject().setValue(context, MemberNames.Designation.toString(), designation);
	}

	/**
	 * @return value of DateOfJoining
	 */
	public final java.util.Date getDateOfJoining()
	{
		return getDateOfJoining(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfJoining
	 */
	public final java.util.Date getDateOfJoining(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfJoining.toString());
	}

	/**
	 * Set value of DateOfJoining
	 * @param dateofjoining
	 */
	public final void setDateOfJoining(java.util.Date dateofjoining)
	{
		setDateOfJoining(getContext(), dateofjoining);
	}

	/**
	 * Set value of DateOfJoining
	 * @param context
	 * @param dateofjoining
	 */
	public final void setDateOfJoining(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofjoining)
	{
		getMendixObject().setValue(context, MemberNames.DateOfJoining.toString(), dateofjoining);
	}

	/**
	 * @return value of ContactInfo
	 */
	public final java.lang.String getContactInfo()
	{
		return getContactInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of ContactInfo
	 */
	public final java.lang.String getContactInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContactInfo.toString());
	}

	/**
	 * Set value of ContactInfo
	 * @param contactinfo
	 */
	public final void setContactInfo(java.lang.String contactinfo)
	{
		setContactInfo(getContext(), contactinfo);
	}

	/**
	 * Set value of ContactInfo
	 * @param context
	 * @param contactinfo
	 */
	public final void setContactInfo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contactinfo)
	{
		getMendixObject().setValue(context, MemberNames.ContactInfo.toString(), contactinfo);
	}

	/**
	 * @return value of DepartmentName
	 */
	public final java.lang.String getDepartmentName()
	{
		return getDepartmentName(getContext());
	}

	/**
	 * @param context
	 * @return value of DepartmentName
	 */
	public final java.lang.String getDepartmentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DepartmentName.toString());
	}

	/**
	 * Set value of DepartmentName
	 * @param departmentname
	 */
	public final void setDepartmentName(java.lang.String departmentname)
	{
		setDepartmentName(getContext(), departmentname);
	}

	/**
	 * Set value of DepartmentName
	 * @param context
	 * @param departmentname
	 */
	public final void setDepartmentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String departmentname)
	{
		getMendixObject().setValue(context, MemberNames.DepartmentName.toString(), departmentname);
	}

	/**
	 * @return value of EmployeeName
	 */
	public final java.lang.String getEmployeeName()
	{
		return getEmployeeName(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeName
	 */
	public final java.lang.String getEmployeeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmployeeName.toString());
	}

	/**
	 * Set value of EmployeeName
	 * @param employeename
	 */
	public final void setEmployeeName(java.lang.String employeename)
	{
		setEmployeeName(getContext(), employeename);
	}

	/**
	 * Set value of EmployeeName
	 * @param context
	 * @param employeename
	 */
	public final void setEmployeeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employeename)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeName.toString(), employeename);
	}

	/**
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress()
	{
		return getEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailAddress.toString());
	}

	/**
	 * Set value of EmailAddress
	 * @param emailaddress
	 */
	public final void setEmailAddress(java.lang.String emailaddress)
	{
		setEmailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of EmailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.EmailAddress.toString(), emailaddress);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_Department
	 */
	public final employeemanagement.proxies.Department getEmployee_Department() throws com.mendix.core.CoreException
	{
		return getEmployee_Department(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Department
	 * @throws com.mendix.core.CoreException
	 */
	public final employeemanagement.proxies.Department getEmployee_Department(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		employeemanagement.proxies.Department result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Department.toString());
		if (identifier != null) {
			result = employeemanagement.proxies.Department.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_Department
	 * @param employee_department
	 */
	public final void setEmployee_Department(employeemanagement.proxies.Department employee_department)
	{
		setEmployee_Department(getContext(), employee_department);
	}

	/**
	 * Set value of Employee_Department
	 * @param context
	 * @param employee_department
	 */
	public final void setEmployee_Department(com.mendix.systemwideinterfaces.core.IContext context, employeemanagement.proxies.Department employee_department)
	{
		if (employee_department == null) {
			getMendixObject().setValue(context, MemberNames.Employee_Department.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_Department.toString(), employee_department.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_Account
	 */
	public final administration.proxies.Account getEmployee_Account() throws com.mendix.core.CoreException
	{
		return getEmployee_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getEmployee_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_Account
	 * @param employee_account
	 */
	public final void setEmployee_Account(administration.proxies.Account employee_account)
	{
		setEmployee_Account(getContext(), employee_account);
	}

	/**
	 * Set value of Employee_Account
	 * @param context
	 * @param employee_account
	 */
	public final void setEmployee_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account employee_account)
	{
		if (employee_account == null) {
			getMendixObject().setValue(context, MemberNames.Employee_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_Account.toString(), employee_account.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return employeeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final employeemanagement.proxies.Employee that = (employeemanagement.proxies.Employee) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
