// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package employeemanagement.proxies;

public enum EmployeeField
{
	EmployeeID(new java.lang.String[][] { new java.lang.String[] { "en_US", "EmployeeID" } }),
	EmployeeName(new java.lang.String[][] { new java.lang.String[] { "en_US", "EmployeeName" } }),
	Department(new java.lang.String[][] { new java.lang.String[] { "en_US", "DepartmentName" } }),
	Designation(new java.lang.String[][] { new java.lang.String[] { "en_US", "Designation" } }),
	ContactInfo(new java.lang.String[][] { new java.lang.String[] { "en_US", "ContactInfo" } }),
	DateOfJoining(new java.lang.String[][] { new java.lang.String[] { "en_US", "DateOfJoining" } }),
	DepartmentID(new java.lang.String[][] { new java.lang.String[] { "en_US", "DepartmentID" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private EmployeeField(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
