// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package employeemanagement.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the EmployeeManagement module

	public static java.lang.String getDB_PASSWORD()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EmployeeManagement.DB_PASSWORD");
	}

	public static java.lang.String getDB_USER_NAME()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EmployeeManagement.DB_USER_NAME");
	}

	public static java.lang.String getGOOGLE_API_KEY()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EmployeeManagement.GOOGLE_API_KEY");
	}

	public static java.lang.String getOPEN_WEATHER_API_KEY()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EmployeeManagement.OPEN_WEATHER_API_KEY");
	}

	public static java.lang.String getPAGE_SIZE()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EmployeeManagement.PAGE_SIZE");
	}

	public static java.lang.String getWEATHER_API()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EmployeeManagement.WEATHER_API");
	}
}