// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package email_connector.proxies;

public class ScopeSelected
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject scopeSelectedMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Email_Connector.ScopeSelected";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ScopeString("ScopeString"),
		ScopeSelected_OAuthProvider("Email_Connector.ScopeSelected_OAuthProvider");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ScopeSelected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ScopeSelected(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject scopeSelectedMendixObject)
	{
		if (scopeSelectedMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, scopeSelectedMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.scopeSelectedMendixObject = scopeSelectedMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ScopeSelected.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static email_connector.proxies.ScopeSelected initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return email_connector.proxies.ScopeSelected.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static email_connector.proxies.ScopeSelected initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new email_connector.proxies.ScopeSelected(context, mendixObject);
	}

	public static email_connector.proxies.ScopeSelected load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return email_connector.proxies.ScopeSelected.initialize(context, mendixObject);
	}

	public static java.util.List<email_connector.proxies.ScopeSelected> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> email_connector.proxies.ScopeSelected.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ScopeString
	 */
	public final java.lang.String getScopeString()
	{
		return getScopeString(getContext());
	}

	/**
	 * @param context
	 * @return value of ScopeString
	 */
	public final java.lang.String getScopeString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ScopeString.toString());
	}

	/**
	 * Set value of ScopeString
	 * @param scopestring
	 */
	public final void setScopeString(java.lang.String scopestring)
	{
		setScopeString(getContext(), scopestring);
	}

	/**
	 * Set value of ScopeString
	 * @param context
	 * @param scopestring
	 */
	public final void setScopeString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scopestring)
	{
		getMendixObject().setValue(context, MemberNames.ScopeString.toString(), scopestring);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ScopeSelected_OAuthProvider
	 */
	public final email_connector.proxies.OAuthProvider getScopeSelected_OAuthProvider() throws com.mendix.core.CoreException
	{
		return getScopeSelected_OAuthProvider(getContext());
	}

	/**
	 * @param context
	 * @return value of ScopeSelected_OAuthProvider
	 * @throws com.mendix.core.CoreException
	 */
	public final email_connector.proxies.OAuthProvider getScopeSelected_OAuthProvider(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		email_connector.proxies.OAuthProvider result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ScopeSelected_OAuthProvider.toString());
		if (identifier != null) {
			result = email_connector.proxies.OAuthProvider.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ScopeSelected_OAuthProvider
	 * @param scopeselected_oauthprovider
	 */
	public final void setScopeSelected_OAuthProvider(email_connector.proxies.OAuthProvider scopeselected_oauthprovider)
	{
		setScopeSelected_OAuthProvider(getContext(), scopeselected_oauthprovider);
	}

	/**
	 * Set value of ScopeSelected_OAuthProvider
	 * @param context
	 * @param scopeselected_oauthprovider
	 */
	public final void setScopeSelected_OAuthProvider(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.OAuthProvider scopeselected_oauthprovider)
	{
		if (scopeselected_oauthprovider == null) {
			getMendixObject().setValue(context, MemberNames.ScopeSelected_OAuthProvider.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ScopeSelected_OAuthProvider.toString(), scopeselected_oauthprovider.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return scopeSelectedMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final email_connector.proxies.ScopeSelected that = (email_connector.proxies.ScopeSelected) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
